collections:
  lecture-notes:
    output:
      true
  books:
    output:
      true
  projects:
    output:
      true

defaults:
  - scope:
      path: ""
      type: "lecture-notes"
    values:
      layout: "lecture-notes"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - scripts/
