title: "keuchel.dev"
description: "Personal Webpage of Jan Keuchel"
url: "https://keuchel.dev"

baseurl: ""


collections:
  lecture-notes:
    output:
      true
  books:
    output:
      true
  projects:
    output:
      true

defaults:
  - scope:
      path: ""
      type: "lecture-notes"
    values:
      layout: "lecture-notes"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  toc_levels: 2..3

exclude:
  - scripts/
  - working_files/
